builds:
  - main: ./cmd/ejson/
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.VERSION={{.Version}} -extldflags "-static"
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - freebsd
      - linux
      - windows
    goarch:
      - amd64
      - arm64
